# Basic Python

## 1. Split this string

Output should be a List: ['Hi', 'there', 'Sam!']

In [4]:
s = "Hi there Sam!"

In [31]:
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

 Output should be: The diameter of Earth is 12742 kilometers.

In [8]:
planet = "Earth"
diameter = 12742

In [34]:
str='The diameter of {planet} is {diameter} kilometers'.format(planet='Earth',diameter=12742)
str

'The diameter of Earth is 12742 kilometers'

# 3. In this nest dictionary grab the word "hello"

In [15]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [47]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [18]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [51]:
arr_1=np.zeros(10,dtype=int)
arr_1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
arr_2=np.ones(10,dtype=int)*5
arr_2

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## 5. Create an array of all the even integers from 20 to 35

In [55]:
print(np.arange(20,35,2))

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [58]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [70]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [82]:
ctc={'infosys':400000,
    'accenture':450000,
    'zoho':500000}
salary=pd.Series(ctc)
emp_dict={'infosys':3500,
    'accenture':4500,
    'zoho':5000}
empid=pd.Series(emp_dict)
company=pd.DataFrame({'ctc':salary,'empid':empid})
company

ctc  empid
infosys    400000   3500
accenture  450000   4500
zoho       500000   5000

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [76]:
import pandas as pd
from datetime import date, timedelta
sdate = date(2023,1,1)   # start date
edate = date(2023,2,10)   # end date
pd.date_range(sdate,edate-timedelta(days=1),freq='d')



DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09'],
              dtype='datetime64[ns]', freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [79]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [80]:
pd.DataFrame(lists)

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24